### ISSUE TITLE
pycolmap has moved into colmap/colmap

### ISSUE THREAD

**Issue by HernandoR** [conda-forge/pycolmap-feedstock#38]
### Comment:

As described in [colmap/pycolmap](https://github.com/colmap/pycolmap) it has migrated to the main repo, [colmap/colmap](https://github.com/colmap/colmap); should we worry about the package outdated, and try to move the source of pycolmap to colmap?

**Comment by HernandoR** [comment]
> Yes please - are you happy to give it a go @HernandoR?

Sure,  I will give it a try, but I have never written a conda recipe before, so you may need to pay extra attention to review my pr introducing serious bugs.

**Comment by HernandoR** [comment]
@Tobias-Fischer Do you mind check out on https://github.com/HernandoR/pycolmap-feedstock/issues/1 ?

i'm totally lost, don't know where referance to or what to do on next step.

**Comment by Tobias-Fischer** [comment]
Can you please create a pull request here in the repository? Then we can debug here and see what’s going on in CI.

**Comment by Tobias-Fischer** [comment]
All done :)
